name = "commmob-ai-worker"
main = "cloudflare-ai-worker.js"
compatibility_date = "2024-01-15"

# AI binding for Cloudflare Workers AI
[[ai]]
binding = "AI"

# Environment variables (set these in Cloudflare dashboard or via wrangler)
[vars]
ENVIRONMENT = "production"

# Optional: Custom domain
# route = "ai.yourdomain.com/*"

# Optional: KV storage for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
